export const FETCH_CURRENTCITY_START = 'FETCH_CURRENTCITY_START';
export const FETCH_CURRENTCITY_SUCCESS = 'FETCH_CURRENTCITY_SUCCESS';
export const FETCH_CURRENTCITY_FAIL = 'FETCH_CURRENTCITY_FAIL';

export const FETCH_CITIES_START = 'FETCH_CITIES_START';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL';

export const TOGGLE_BUTTON = 'TOGGLE_BUTTON';

export const ADD_CITY_START = 'ADD_CITY_START';
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS';
export const ADD_CITY_FAIL = 'ADD_CITY_FAIL';

export const DELETE_CITY_START = 'DELETE_CITY_START';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const DELETE_CITY_FAIL = 'DELETE_CITY_FAIL';

export const SELECT_CITY = 'SELECT_CITY';

export const ADD_BUTTON = 'ADD_BUTTON';
export const CANCEL_BUTTON = 'CANCEL_BUTTON';


export const FETCH_CURRENTCITY_WEATHER_START = 'FETCH_CURRENTCITY_WEATHER_START';
export const FETCH_CURRENTCITY_WEATHER_SUCCESS = 'FETCH_CURRENTCITY_WEATHER_SUCCESS';
export const FETCH_CURRENTCITY_WEATHER_FAIL = 'FETCH_CURRENTCITY_WEATHER_FAIL';

export const FETCH_MORECITIES_WEATHER_START = 'FETCH_MORECITIES_WEATHER_START';
export const FETCH_MORECITIES_WEATHER_SUCCESS = 'FETCH_MORECITIES_WEATHER_SUCCESS';
export const FETCH_MORECITIES_WEATHER_FAIL = 'FETCH_MORECITIES_WEATHER_FAIL';

export const FETCH_CITY_WEATHER_START = 'FETCH_CITY_WEATHER_START';
export const FETCH_CITY_WEATHER_SUCCESS = 'FETCH_CITY_WEATHER_SUCCESS';
export const FETCH_CITY_WEATHER_FAIL = 'FETCH_CITY_WEATHER_FAIL';

